force-app/main/default/objects/Account/fields/FHIRdata1__c.field-meta.xml
<CustomField>
    <fullName>FHIRdata1__c</fullName>
    <label>FHIRdata1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/HealthCloudGA__MedicalRecordNumber__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__MedicalRecordNumber__c</fullName>
    <description>The medical record number is organization specific. The number is used by the hospital as a systematic documentation of a patient´s medical history and care during each hospital stay.</description>
    <label>Medical Record Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPIC_Access__c/EPIC_Access__c.object-meta.xml
<CustomObject>
    <label>EPIC Access</label>
    <nameField>
        <label>EPIC Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epic Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EPIC_Access__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EPIC_Access__c/fields/ExpireEpoch__c.field-meta.xml
<CustomField>
    <fullName>ExpireEpoch__c</fullName>
    <label>ExpireEpoch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EPIC_Access__c/fields/Expires_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Expires_In_Seconds__c</fullName>
    <label>Expires In Seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/FHIR_JWT_SETTINGS__mdt.object-meta.xml
<CustomObject>
    <label>FHIR_jwt_setting</label>
    <pluralLabel>FHIR_jwt_settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/fields/AUD__c.field-meta.xml
<CustomField>
    <fullName>AUD__c</fullName>
    <description>The FHIR authorization server&apos;s token endpoint URL. This is the same URL to which this authentication JWT will be posted. See below for an example POST.</description>
    <inlineHelpText>The FHIR authorization server&apos;s token endpoint URL. This is the same URL to which this authentication JWT will be posted. See below for an example POST.</inlineHelpText>
    <label>AUD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/fields/Cert_Name__c.field-meta.xml
<CustomField>
    <fullName>Cert_Name__c</fullName>
    <description>Text name of the cert you want to use to sign the JWT.  Needs to be in the Certs settings.</description>
    <inlineHelpText>Text name of the cert you want to use to sign the JWT.  Needs to be in the Certs settings.</inlineHelpText>
    <label>Cert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/fields/ISS__c.field-meta.xml
<CustomField>
    <fullName>ISS__c</fullName>
    <description>Issuer of the JWT. This is the app&apos;s client_id, as determined during registration on the Epic on FHIR website.</description>
    <inlineHelpText>Issuer of the JWT. This is the app&apos;s client_id, as determined during registration on the Epic on FHIR website.</inlineHelpText>
    <label>ISS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/fields/JTI__c.field-meta.xml
<CustomField>
    <fullName>JTI__c</fullName>
    <description>A unique identifier for the JWT.</description>
    <inlineHelpText>A unique identifier for the JWT.</inlineHelpText>
    <label>JTI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FHIR_JWT_SETTINGS__mdt/fields/SUB__c.field-meta.xml
<CustomField>
    <fullName>SUB__c</fullName>
    <description>The service&apos;s client_id, as determined during registration on the Epic on FHIR website.</description>
    <inlineHelpText>The service&apos;s client_id, as determined during registration on the Epic on FHIR website.</inlineHelpText>
    <label>SUB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FHIRdemoHelper.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

global with sharing class FHIRdemoHelper {
        @InvocableVariable(required=true)
        global String firstName;
    
        @InvocableVariable(required=true)
        global String lastName;
    
        @InvocableVariable(required=true)
        global DateTime dob;
    private static 	FHIR_JWT_SETTINGS__mdt FHIRjwtSettings;
   
    public static FHIR_JWT_SETTINGS__mdt settings() {
        if(FHIRjwtSettings == null) {
            FHIRjwtSettings = [
                SELECT  MasterLabel, AUD__c, ISS__c, 
                        SUB__c, JTI__c,
                        Cert_Name__c
                FROM    FHIR_JWT_SETTINGS__mdt 
                WHERE   MasterLabel = 'FHIR Settings'
            ];
        }
        return FHIRjwtSettings;
    }
    @InvocableMethod(label='Get Patient Details from Epic Part2' description='Opens a connection to Epic via FHIR and pulls in appropriate data.' category='Account')
    global static void getUserDetail(){
        
    
    
        String errorMessage ='';
        Http http = new Http();
        HttpRequest httpReq = new HttpRequest();
        HttpResponse httpRes = new HttpResponse();
        
        List<Epic_Access__c> EpicAccessListNew = [Select Id, Name,Access_Token__c,Expires_In_Seconds__c,ExpireEpoch__c  From EPIC_Access__c Where Name='EPICAccess'];
        
        httpReq.SetMethod('GET');
        httpReq.setEndpoint('https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/STU3/Patient/eq081-VQEgP8drUUqCWzHfw3');
        httpReq.setHeader('Authorization', 'Bearer '+ EpicAccessListNew[0].Access_Token__c);
        httpReq.setHeader('Content-Type', 'application/json');
        System.debug('Bearer '+ EpicAccessListNew[0].Access_Token__c);
        try{
            httpRes = http.send(httpReq);
            if(httpRes.getStatusCode() == 200){
                JSONParse root = new JSONParse(httpRes.getBody());
                
                //BasicInfo = 'Patient Name: ' + root.get('name').get('[1].text').getStringValue() + 'has been updated via FHIR connection to EPIC'; //Get Name
                String pcity = root.get('birthDate').getStringValue(); 
                String tel = root.get('telecom').get('[0].value').getStringValue();

                //String add1 = root.get('address').get('line').getStringValue() + ',' + root.get('address').get('city').getStringValue() + ',' + root.get('address').get('state').getStringValue() + ',' + root.get('address').get('postalCode').getStringValue();

                System.debug('Birthdate is: ' + date.valueOf(pcity));
                Account accounttoUpdate;
                accounttoUpdate = [SELECT PersonBirthdate, FHIRdata1__c FROM Account WHERE FirstName = 'Derrick'];
                accounttoUpdate.PersonBirthdate = date.valueOf(pcity);
                accounttoUpdate.FHIRdata1__c = root.toStringPretty();
                accounttoUpdate.Phone = tel;
                accounttoUpdate.Member_ID__pc = root.get('identifier').get('[5].value').getStringValue();
                accounttoUpdate.HealthCloudGA__MedicalRecordNumber__pc = root.get('id').getStringValue();
                accounttoUpdate.Member_ID__c = root.get('identifier').get('[5].value').getStringValue();
                accounttoUpdate.HealthCloudGA__MedicalRecordNumber__c = root.get('id').getStringValue();
                accounttoUpdate.HealthCloudGA__Gender__pc = root.get('gender').getStringValue();
                //accounttoUpdate.BillingAddress = add1;


                update accounttoUpdate;
              
            }else{
                errorMessage = 'Unexpected Error while communicating with LinkedIn API. '
                                    +'Status '+httpRes.getStatus()+' and Status Code '+httpRes.getStatuscode();
            }
        }catch(System.Exception e){
            System.debug('#### Exception Excuted '+e.getStackTraceString()+'  '+e.getMessage());
            if(String.valueOf(e.getMessage()).startsWith('Unauthorized endpoint')){
                errorMessage =  'Unauthorize endpoint: An Administer must go to Setup -> Administer -> Security Control ->'
                                    +' Remote Site Setting and add '+' '+ 'https://api.linkedin.com/ '+' Endpoint';
            }else{
                errorMessage = 'Unexpected Error while communicating with LinkedIn API. '
                                    +'Status '+httpRes.getStatus()+' and Status Code '+httpRes.getStatuscode();
            }
        }
        
    }

    


}